culturagovbr/salic-minc

- application/modules/parecer/controllers/AnaliseCnicController.php
> [UPDATE] Parecer: ajuste na finalização de parecer para D50

- application/modules/default/models/spPlanilhaOrcamentaria.php
- application/modules/proposta/models/DbTable/TbPlanilhaProposta.php
Consultar projetos: exibindo planilha aprovada corretamente
Adequação de proposta: arredondando valores da totalização da planilha da proposta
> Hotfix encaminhar projeto cultural

- application/modules/agente/views/scripts/agentes/enderecos.phtml
- application/modules/agente/views/scripts/agentes/partials/form-incluir-agente.phtml
- application/modules/default/controllers/CepController.php
- public/js/agentes.js
- public/js/manteragentes.js
Correções nos formulário de agentes
> Hotfix cadastro agentes

- application/modules/default/controllers/RealizarprestacaodecontasController.php
- application/modules/default/models/PlanilhaAprovacao.php
- application/modules/default/views/scripts/realizarprestacaodecontas/analisar-comprovacao.phtml
- application/modules/default/views/scripts/realizarprestacaodecontas/laudofinal.phtml
- application/modules/default/views/scripts/realizarprestacaodecontas/planilha-orcamentaria-custos-produto.phtml
- application/modules/default/views/scripts/realizarprestacaodecontas/planilha-orcamentaria-custos.phtml
- application/modules/default/views/scripts/realizarprestacaodecontas/planilha-orcamentaria-tabela.phtml
- application/modules/default/views/scripts/realizarprestacaodecontas/planilhaorcamentaria.phtml
- application/modules/prestacao-contas/controllers/VisualizarProjetoController.php
- public/js/vue.js
Finalização de prestação de contas
> Fix menu prestacao contas

- _posts/2017-12-26-missao-php-7.markdown
Algumas correções rápidas no texto.
> Atualizando texto da missão para php 7

- tests/application/modules/proposta/controllers/PlanoDistribuicaoControllerTest.php
Teste detalhar plano distribuição.
> [UPDATE] #206 Teste detalhar plano distribuição

- application/modules/default/models/Inabilitado.php
- application/modules/proposta/views/scripts/planodistribuicao/index.phtml
[Projeto] Arrumando a consulta SQL em Consultar Dados Projeto.
> Feature plano distribuicao

- doc/Teste_Manual.md
Alterações no manual de teste mais exemplos de testes possíveis.
> Feature manual test

- doc/Teste_Manual.md
Acionando exemplos para configurar os testes.
> [UPDATE] Exemplo configuração de testes

- application/configs/exemplo-application.ini
- application/modules/default/models/Inabilitado.php
- application/modules/default/models/PlanoDistribuicao.php
- application/modules/default/models/Projetos.php
- application/modules/proposta/controllers/PlanoDistribuicaoController.php
- application/modules/proposta/models/DbTable/PreProjeto.php
- application/modules/proposta/views/scripts/plano-distribuicao/detalhar-plano-distribuicao.phtml
- application/modules/proposta/views/scripts/planodistribuicao/index.phtml
- public/scripts/proposta/plano-distribuicao/detalhar-plano-distribuicao.js
- tests/application/modules/projeto/controllers/ConsultardadosprojetoControllerTest.php
- tests/application/modules/proposta/controllers/PlanoDistribuicaoControllerTest.php
Nova funcionalidade segundo IN.
> [Proposta] Plano de Distribuicao

- application/modules/proposta/controllers/ManterpropostaincentivofiscalController.php
- application/modules/proposta/models/DbTable/PreProjeto.php
- application/modules/proposta/views/scripts/manterpropostaincentivofiscal/declaracaonovaproposta.phtml
- application/modules/proposta/views/scripts/manterpropostaincentivofiscal/detalhestecnicos.phtml
- application/modules/proposta/views/scripts/manterpropostaincentivofiscal/identificacaodaproposta.phtml
- application/modules/proposta/views/scripts/manterpropostaincentivofiscal/outrasinformacoes.phtml
- application/modules/proposta/views/scripts/manterpropostaincentivofiscal/responsabilidadesocial.phtml
- tests/application/modules/proposta/controllers/ManterpropostaincentivofiscalControllerTest.php
Resolvendo as issues #263 e #264, @isaiassm e @guiamado.
> Feature formulario proposta

- application/modules/admissibilidade/models/DbTable/TbMensagemProjeto.php
- application/modules/admissibilidade/models/Enquadramento.php
- application/modules/default/models/spPlanilhaOrcamentaria.php
- application/modules/proposta/views/scripts/visualizar-plano-distribuicao/visualizar.phtml
- public/css/_colors.css
- public/css/_forms.css
- public/css/_tables.css
> Feature ajustes gerais

- application/modules/admissibilidade/controllers/EnquadramentoPropostaController.php
- application/modules/admissibilidade/views/scripts/enquadramento-proposta/historico-sugestao-enquadramento.phtml
- application/modules/admissibilidade/views/scripts/enquadramento-proposta/sugerir-enquadramento.phtml
> Feature historico sugestao enquadramento

- application/configs/layout.ini
- application/modules/admissibilidade/views/scripts/admissibilidade/proposta-por-incentivo-fiscal.phtml
- application/modules/autenticacao/models/Grupos.php
- application/modules/default/views/scripts/manterusuario/perfissalicweb.phtml
- application/modules/proposta/views/scripts/manterpropostaedital/enviararquivoedital.phtml
- application/modules/proposta/views/scripts/manterpropostaincentivofiscal/identificacaodaproposta.phtml
- public/css/_reset.css
- public/css/_sidebar.css
- public/library/materialize/js/materialize-ready.js
Proposta: Correção de bug ao anexar documento na proposta #350 
Admissibilidade: mostrando botões de `Transformar em Projeto` e `Arquivar` apenas para coordenadores #296
> Hotfix sql zend

- application/modules/admissibilidade/controllers/AdmissibilidadeController.php
- application/modules/admissibilidade/models/DbTable/VwPainelAvaliarPropostas.php
- application/modules/admissibilidade/views/scripts/admissibilidade/listarpropostas.phtml
- public/js/admissibilidade/enquadramento-proposta/sugerir-enquadramento.js
> Feature refatoracao lista avaliacao

- application/modules/admissibilidade/controllers/EnquadramentoController.php
> [FIX] Correção de erro ao enquadrar projeto. #377

- application/modules/admissibilidade/controllers/EnquadramentoController.php
- application/modules/admissibilidade/views/scripts/enquadramento/encaminhar-assinatura.phtml
> [FIX] Correção do encaminhamento de projeto cultural enquadrado.

- application/modules/default/models/GerarPagamentoParecerista.php
Arrumando parte de Consulta de meus pagamentos no Parecerista.
> [FIX] Parecerista: Arrumando consulta meus pagamentos

- application/modules/admissibilidade/views/scripts/enquadramento-assinatura/gerenciar-assinaturas.phtml
Co-authored by: wouerner <wouerner@protonmail.com>
> [UPDATE] Assinatura: modal-trigger error #456

- application/modules/default/views/scripts/readequacoes/planilha-orcamentaria.phtml
Erro ao solicitar readequação pela primeira vez.
> [UPDATE] Readequação: Planilha orçamentaria

- application/modules/assinatura/views/scripts/index/gerenciar-assinaturas.phtml
#511
Co-authored-by: Fernao <fernao@riseup.net>
> [FIX] Ajuste de exibição de modal ao movimentar uma assinatura.

- application/modules/proposta/controllers/ManterpropostaincentivofiscalController.php
- application/modules/proposta/views/scripts/inc/menu.phtml
> Hotfix envio proposta

- application/modules/proposta/controllers/ManterpropostaincentivofiscalController.php
- application/modules/proposta/views/scripts/inc/menu.phtml
#520
Co-authored-by: Cleber Santos <oclebersantos@gmail.com>
> [FIX] Tratamento para o botão de Enviar Proposta ao Minc.

- application/modules/autenticacao/models/FnVerificarPermissao.php
- application/modules/default/controllers/ListarprojetosController.php
- application/modules/default/views/scripts/listarprojetos/listarprojetos.phtml
- application/modules/projeto/models/DbTable/Projetos.php
- application/modules/proposta/models/DbTable/PreProjeto.php
- application/modules/proposta/views/scripts/inc/menu.phtml
[FIX] Proposta/Excluir Proposta: corrige opção de excluir proposta #517
[FIX] Projeto/Clonar Projeto: disponibiliza para todos os projetos que possuem proposta #145
[REFACTOR] Proposta: melhoria na verificação de acesso à proposta
> Feature ajustes na proposta

- sql/SQLServer/dbchangelog/scripts_a_executar_em_producao/spAtivarPlanilhaOrcamentaria.sql
> [UPDATE] Readequação de planilha: sp para realizar troca de planilhas

- application/modules/default/views/scripts/consultardadosprojeto/extratos-bancarios.phtml
Parte do combobox que nao estava aparecendo
Co-authored-by: isaiassm <isaias1113@outlook.com>
> [FIX] Arrumando campo que nao estava aparecendo #609

- application/modules/default/models/tbComunicados.php
- application/modules/default/views/scripts/comunicados/ativos.phtml
- application/modules/default/views/scripts/comunicados/desativados.phtml
- application/modules/default/views/scripts/comunicados/editar.phtml
- application/modules/default/views/scripts/comunicados/index.phtml
- application/modules/default/views/scripts/comunicados/listar-comunicados.phtml
- application/modules/default/views/scripts/comunicados/novo.phtml
- application/modules/default/views/scripts/manterusuario/gerarsenha.phtml
Arrumando bugs referentes da issue #655, na parte de gestor do salic em Comunicados Ativos/Desativados.
> Fix comunicados ativos desativados

- application/modules/default/views/scripts/consultardadosprojeto/extrato-conta-movimento-consolidado.phtml
- application/modules/default/views/scripts/consultardadosprojeto/extratos-bancarios.phtml
> Fix extrato bancario

- application/modules/admissibilidade/views/scripts/admissibilidade/imprimir-proposta-por-incentivo-fiscal.phtml
> Fix gerar pdf

- tests/application/modules/admissibilidade/controllers/AdmissibilidadeControllerTest.php
- tests/application/modules/agente/controllers/AgentesControllerTest.php
- tests/application/modules/assinatura/controllers/AssinaturaControllerTest.php
- tests/application/modules/default/controllers/AlterarprojetoControllerTest.php
- tests/application/modules/default/controllers/AnexardocumentosmincControllerTest.php
- tests/application/modules/default/controllers/AreadetrabalhoControllerTest.php
- tests/application/modules/default/controllers/ComunicadosControllerTest.php
- tests/application/modules/default/controllers/ConsultardadosprojetoControllerTest.php
- tests/application/modules/default/controllers/GerarrelatoriopareceristaControllerTest.php
- tests/application/modules/default/controllers/GerarrelatorioreuniaoControllerTest.php
- tests/application/modules/default/controllers/GerenciarpareceresControllerTest.php
- tests/application/modules/default/controllers/GerenciarpautareuniaoControllerTest.php
- tests/application/modules/default/controllers/ListarprojetosControllerTest.php
- tests/application/modules/default/controllers/LocalizacaoFisicaControllerTest.php
- tests/application/modules/default/controllers/MantersecretarioorgoaControllerTest.php
- tests/application/modules/default/controllers/MantertermodecisaoConttrollerTest.php
- tests/application/modules/default/controllers/OperacionalControllerTest.php
- tests/application/modules/default/controllers/RelatorioControllerTest.php
- tests/application/modules/default/controllers/TramitarProjetosControllerTest.php
- tests/application/modules/default/controllers/TramitardocumentosTest.php
- tests/application/modules/proposta/controllers/AnalisarSituacaoItemControllerTest.php
- tests/application/modules/proposta/controllers/ManterorcamentoControllerTest.php
- tests/application/modules/proposta/controllers/ManterpropostaincentivofiscalControllerTest.php
- tests/application/modules/proposta/controllers/PlanoDistribuicaoControllerTest.php
- tests/application/modules/solicitacao/controllers/MensagemControllerTest.php
> Feature adicionando test

- application/modules/default/controllers/ComprovarexecucaofinanceiraController.php
- application/modules/default/views/scripts/comprovarexecucaofinanceira/comprovacaopagamento.phtml
Co-authored-by: Guilherme Amado <amado.guigui@gmail.com>
> [FIX] #795 Erro ao comprovar prestação de contas inicial.

- application/modules/admissibilidade/controllers/AdmissibilidadeController.php
opção de encaminhar proposta para quando ainda não houver distribuições para
Coordenador de Admissibilidade
#831
> :zap: Avaliação de Proposta: Adição de tratamento para para liberar

- doc/primeiros-passos.md
Guilherme <amado.guigui@gmail.com>
Marcos <marcosvanillle@gmail.com>
> [ADD] Primeiros Passos

- git_hooks/pre-push.sh
deployments forem realizados automaticamente
para ambiente de homologação #848
> :zap: Atualização de mensagem padrão para quando

- application/modules/prestacao-contas/controllers/GerenciarController.php
- application/modules/prestacao-contas/views/scripts/partials/tabelaItens.phtml
excluir não estavam aparecendo na comprovação.
> [FIX] Prestaçao de Contas: Erro na prestação de contas botões editar e

- application/modules/proposta/controllers/PreProjetoArquivadoController.php
Co-authored-by: Marcos <marcosvanillle@gmail.com>
Referente ao Hotfix da issue #861
> [FIX] Arrumando Texto de email de arquivamento de proposta #861

- application/modules/admissibilidade/controllers/AdmissibilidadeController.php
- application/modules/projeto/models/DbTable/Projetos.php
- application/modules/recurso/models/DbTable/TbRecursoProposta.php
de enquadramento da proposta no enquadramento do projeto.
:zap: Alteração de situação para 'B04' conforme solicitado na Issue #874
> :bug: Transformação de proposta em projeto: Armazenamento de sugestão

- application/modules/default/views/scripts/comprovarexecucaofinanceira/pagamento.phtml
- application/modules/diligencia/views/scripts/gerenciar/responder.phtml
- application/modules/prestacao-contas/controllers/PagamentoController.php
- application/modules/prestacao-contas/views/scripts/pagamento/index.phtml
> F/prestacao contas/dev guiamado

- application/modules/default/models/PlanilhaAprovacao.php
estavam sendo ignorados.
Co-authored-by: Fernao <fernao@gmail.com>
> [FIX] erros nas planilhas que não tem alterações em seus itens, esses

- application/modules/default/models/PlanilhaAprovacao.php
- application/modules/prestacao-contas/controllers/PagamentoController.php
Arrumando charset que estava quebrando somento no produto.
> [FIX] Arrumando bug em que o produto tinha charset quebrado #844

- application/modules/default/views/scripts/localizacao-fisica/index.phtml
> [FIX] Arrumando botões congelados #905

- application/modules/default/models/PlanilhaAprovacao.php
- application/modules/prestacao-contas/views/scripts/gerenciar/comprovar.phtml
- public/scripts/prestacao-contas/comprovacaopagamento.js
> [FIX] Prestação de Contas: #864 valores decimais da consulta SQL e

- application/modules/prestacao-contas/controllers/GerenciarController.php
> [FIX] Prestação de Contas: #864 erros no backend, exception incorreta na

- application/modules/prestacao-contas/controllers/PagamentoController.php
Refatorando partes que não são mais utilizadas.
> [REFACTOR] Retirando Actions que não estão sendo utilizadas #948 #949

- application/modules/admissibilidade/controllers/AdmissibilidadeController.php
[FIX] Projeto: atualiza área e segmento do projeto e plano distribuição após enquadramento #984
> [HOTFIX] Enquadramento #984

- application/modules/prestacao-contas/controllers/PrestacaoContasController.php
- application/modules/prestacao-contas/controllers/RealizarPrestacaoContasController.php
> Usa spComprovacaoFinanceiraProjeto para buscar todos os comprovantes.

- application/modules/assinatura/controllers/IndexController.php
- application/modules/assinatura/models/DbTable/TbAssinatura.php
- application/modules/assinatura/views/scripts/index/gerenciar-assinaturas.phtml
- application/modules/projeto/controllers/HomologacaoController.php
- application/modules/readequacao/controllers/ReadequacaoAssinaturaController.php
#1042
Co-authored-by: Pedro Philipe Alves de Oliveira <pedrophilipe.ti@gmail.com>
> :zap: Melhoria na listagem de assinatura

- application/modules/assinatura/views/scripts/index/gerenciar-assinaturas.phtml
> :bug: Correção de exibição de botão indevido na lista de projetos para

- doc/Guia_de_operacao-desenvolvimento.md
de desenvolvimento utilizando o Git Workflow
> :zap: [UPDATE] Atualização do guia

- README.md
> Adição de Badge para acompanhamento

- application/modules/readequacao/service/assinatura/DocumentoAssinatura.php
> :zap: Tratamento de título do documento de acordo com o tipo de ato

- application/modules/assinatura/models/DbTable/TbAssinatura.php
- application/modules/assinatura/views/scripts/index/gerenciar-assinaturas.phtml
assinaturas já foram concretizadas
. #1106
> :zap: Dando visibilidade da quantidade total de assinaturas e quantas

- application/modules/default/models/Mensagem.php
- application/modules/proposta/controllers/DiligenciarController.php
- library/MinC/Notification/Message.php
diligência para dispositivos mobile. #1112
Co-Authored-By: Pedro <pedrophilipe.ti@gmail.com>
Co-Authored-By: Paulo <paulotux.mendes@gmail.com>
> :bug: Correção de erro legado que impedia envio de notificação de

- application/modules/readequacao/service/assinatura/acao/Encaminhar.php
SAV o orgão de destino é 682 e quando for SEFIC o órgão de destino será
341.
#896
> :zap: Conforme solicitado pelo Rômulo, quando o órgão superior for

- application/modules/parecer/controllers/AnaliseInicialController.php
projeto para assinatura.
#1126
> :zap: Correção de erro que impossibilitava o encaminhamento de um

- exemplo.docker-compose.yml
> :zap: Correção de definição de variáveis de ambiente através do

- application/modules/readequacao/service/assinatura/acao/Finalizar.php
#1160
Co-Authored-By: Pedro Philipe <pedrophilipeti@gmail.com>
> :zap: Modificação de Órgão de destino e situação de Readequação.

- application/modules/parecer/service/assinatura/analise-inicial/acao/Finalizar.php
> :zap: Conforme solicitado, foram adicionadas alterações na tabela

- application/modules/default/models/tbDistribuirParecer.php
- application/modules/parecer/service/assinatura/analise-inicial/acao/Finalizar.php
> :zap: Ajuste realizado na finalização das assinaturas.

- application/layouts/scripts/partials/menu/menu-prestacao-contas.phtml
- front/src/modules/avaliacao-resultados/components/EmitirParecer.vue
De acordo com issue #1144 Foram removidas as funcionalidade e renomeado o link do menu.
> F/avaliacao resultado/remocao/dev volthier

- application/modules/readequacao/service/assinatura/acao/Finalizar.php
#1160
Co-authored-by: Fernao Lopes <fernao@riseup.net>
Co-authored-by: Paulo Henrique <paulotux.mendes@gmail.com>
> :bug: Correção de falha ao finalizar Assinatura de readequação.

- application/modules/agente/models/DbTable/Visao.php
Co-authored-by: Ruan <ruannawe95@gmail.com>
Co-authored-by: Pedro <pedrophilipe.ti@gmail.com>
> [ FIX ] Arrumando Hotfix de Visão do agente #1236

- application/layouts/scripts/partials/footer.phtml
> Apontamento do Link Desenvolvimento

- front/src/modules/avaliacaoResultados/store/actions.js
Co-authored-by: Volthier <volthier@gmail.com>
> [UPDATE] ESLINT

- application/modules/default/controllers/AlterarprojetoController.php
Co-authored-by: Cleber <oclebersantos@gmail.com>
> [ FIX ] Resolvendo projeto sem agente

- front/src/modules/avaliacaoResultados/components/ConsolidacaoAnalise.vue
> [UPDATE] Inserindo os dados das tabelas do componente

- front/src/modules/avaliacaoResultados/components/AnalisarItem.vue
- front/src/modules/avaliacaoResultados/components/ComponenteEncaminhar.vue
- front/src/modules/avaliacaoResultados/components/Painel.vue
- front/src/modules/avaliacaoResultados/components/Planilha.vue
- front/src/modules/avaliacaoResultados/components/TabelaProjetos.vue
- front/src/modules/avaliacaoResultados/components/TipoAvaliacao.vue
Co-authored-by: Marcos <marcosvanillle@gmail.com>
Co-authored-by: Luiz F. <luiz.pinheiro@cultura.gov.br>
> [ADD] Melhoria de fluxo

- application/modules/avaliacao-resultados/controllers/LaudoController.php
- application/modules/avaliacao-resultados/models/DbTable/LaudoFinal.php
- application/modules/avaliacao-resultados/service/laudo-final/Laudo.php
- front/src/components/menu-superior/index.vue
- front/src/modules/avaliacaoResultados/components/Laudo.vue
Tabela Laudo Final consumindo informações corretas do endpoint avaliacao-resultados/laudo
> Avaliacao resultados fix luiz

- front/src/modules/avaliacaoResultados/components/ComponenteEncaminhar.vue
Co-authored-by: Luiz F Pinheiro <luizfelipenet@hotmail.com>
> [ADD] corrigindo componente de encaminhamento de projeto

- library/MinC/Servico/IServico.php
Co-authored-by: Vinicius Feitosa da Silva <viniciusfesil@gmail.com>
> [ADD] Adição de interface IServico.

- exemplo.docker-compose.yml
Co-authored-by: Vini <viniciusfesil@gmail.com>
> [ADD] Exemplo do arquivo docker-compose

- application/modules/avaliacao-resultados/controllers/ProjetoController.php
- application/modules/avaliacao-resultados/events/Devolver.php
- front/src/helpers/api/AvaliacaoResultados.js
- front/src/modules/avaliacaoResultados/components/Devolver.vue
- front/src/modules/avaliacaoResultados/components/Painel.vue
- front/src/modules/avaliacaoResultados/store/actions.js
Co-authored-by: Wouerner <wouerner@protonmail.com>
Co-authored-by: Fernanda <fernandalassis21@gmail.com>
Co-authored-by: Pedro <pedrophilipe.ti@gmail.com>
> [UPDATE] Invalidando Documento ao devolver projeto para análise

- application/modules/avaliacao-resultados/events/FinalizarParecer.php
- application/modules/avaliacao-resultados/service/parecer-tecnico/AvaliacaoFinanceira.php
- front/src/modules/avaliacaoResultados/components/EmitirParecer.vue
[FIX] Correção dos metodos de finalização do parecer!
> [FIX] Correção dos metodos do Parecer Finalizar!

- application/modules/avaliacao-resultados/service/assinatura/laudo/DocumentoAssinatura.php
Co-authored-by: Wouerner <wouerner@protonmail.com>
> [FIX] Correção no tipo de dado, durante assinatura

- application/modules/avaliacao-resultados/models/LaudoFinal.php
- application/modules/avaliacao-resultados/service/assinatura/laudo/acao/Finalizar.php
- application/modules/projeto/models/Situacao.php
…o final #1776
Co-authored-by: Leonardo Volthier <volthier@gmail.com>
> [assinatura] ação ao finalizar laudo final

- application/modules/projeto/controllers/HomologacaoController.php
- application/modules/proposta/controllers/LocalderealizacaoController.php
- application/modules/proposta/controllers/PlanoDistribuicaoController.php
- application/modules/proposta/models/DbTable/Abrangencia.php
- application/modules/proposta/models/DbTable/TbDetalhaPlanoDistribuicao.php
- application/modules/proposta/models/TbDetalhaPlanoDistribuicaoMapper.php
Ao alterar o local de realização o sistema deve refletir as mudanças no detalhamento do plano de distribuição. Atualmente os valores ficam zerados.
Ao excluir um local de realização com detalhamento, o sistema deve excluir também os detalhamentos da localização. #1889
> Ajustes ao editar/excluir local de realizacao #1889

- front/src/modules/autenticacao/login/login.vue
Co-authored-by: Wouerner Brandão <wouerner@protonmail.com>
> [FIX] Corrigindo padrão de assignments

- api/composer.json
- api/routes/web.php
- docker/php-fpm/Dockerfile
- exemplo.docker-compose.yml
Adicionando configurações para subir os container: php-fpm, salic-web e nginx.
Vamos iniciar dentro do salic o uso do lumen servindo de backend
> [UPDATE] Alguns ajustes para nova API

- application/modules/autenticacao/controllers/UsuarioController.php
- application/modules/navegacao/controllers/MenuPrincipalController.php
- application/modules/readequacao/controllers/CampoAtualController.php
- application/modules/readequacao/controllers/TiposDisponiveisController.php
- application/modules/readequacao/models/DbTable/TbReadequacao.php
- application/modules/readequacao/models/DbTable/TbTipoReadequacao.php
- application/modules/readequacao/service/readequacao/Readequacao.php
- front/src/components/layout/header/HeaderMenuPrincipalSidebar.vue
- front/src/components/layout/header/HeaderMenuPrincipalToolbar.vue
- front/src/components/layout/store/mutations.js
- front/src/helpers/mock/readequacao.md
- front/src/modules/readequacao/components/CriarReadequacao.vue
- front/src/modules/readequacao/components/EditarReadequacaoButton.vue
- front/src/modules/readequacao/components/TemplateDate.vue
- front/src/modules/readequacao/components/TemplateTextarea.vue
- front/src/modules/readequacao/store/actions.js
- front/src/modules/readequacao/views/PainelReadequacoesView.vue
- Atualização com a branch dev
- Implementação das rotas de readequacao
- Correções dos mocks da API - Readequações
> F/readequacao migracao front/diversas

- doc/Seriço NF-e.md
> Docs serviço NFe

- .dockerignore
- Dockerfile
- application/configs/exemplo-application.ini
- docker/salic-web/actions/docker-entrypoint.sh
- exemplo.docker-compose.yml
Co-authored-by: Cleber Santos <oclebersantos@gmail.com>
> [PR] Ajustes de estrutura do docker.

- application/modules/default/controllers/ProjetosController.php
- application/modules/default/views/scripts/verprojetos/documentos-anexados.phtml
- application/modules/default/views/scripts/verprojetos/index.phtml
… documentos anexados no módulo verSalic
> Ajuste visualizar documentos - MTUR302019-1759
